-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 07:44:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SubSistemaSeguridad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SubSistemaSeguridad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SubSistemaSeguridad` DEFAULT CHARACTER SET utf8 ;
USE `SubSistemaSeguridad` ;

-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `correo` BLOB NULL,
  `usuario` BLOB NULL,
  `password` BLOB NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Modulos` (
  `idModulos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idModulos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Aplicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Aplicaciones` (
  `idAplicaciones` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `idModulos` INT NOT NULL,
  PRIMARY KEY (`idAplicaciones`),
  CONSTRAINT `fk_Aplicaciones_Modulos1`
    FOREIGN KEY (`idModulos`)
    REFERENCES `SubSistemaSeguridad`.`Modulos` (`idModulos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Perfil_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Perfil_Detalle` (
  `idPerfil_Detalle` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idPerfil` INT NOT NULL,
  `idAplicaciones` INT NOT NULL,
  PRIMARY KEY (`idPerfil_Detalle`),
  CONSTRAINT `fk_Perfil_Detalle_Perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `SubSistemaSeguridad`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_Detalle_Aplicaciones1`
    FOREIGN KEY (`idAplicaciones`)
    REFERENCES `SubSistemaSeguridad`.`Aplicaciones` (`idAplicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Roles` (
  `idRoles` INT NOT NULL,
  `insert` TINYINT NULL,
  `select` TINYINT NULL,
  `update` TINYINT NULL,
  `delete` TINYINT NULL,
  `print` TINYINT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Asignacion_Perfiles_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Asignacion_Perfiles_Usuarios` (
  `idPerfil` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  `idRoles` INT NOT NULL,
  PRIMARY KEY (`idPerfil`, `idUsuarios`),
  CONSTRAINT `fk_Asignacion_Perfiles_Usuarios_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `SubSistemaSeguridad`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Perfiles_Usuarios_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SubSistemaSeguridad`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Perfiles_Usuarios_Roles1`
    FOREIGN KEY (`idRoles`)
    REFERENCES `SubSistemaSeguridad`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Asignacion_Aplicaciones_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Asignacion_Aplicaciones_Usuarios` (
  `idAplicaciones` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idAplicaciones`, `idUsuarios`),
  CONSTRAINT `fk_Asignacion_Aplicaciones_Usuarios_Aplicaciones1`
    FOREIGN KEY (`idAplicaciones`)
    REFERENCES `SubSistemaSeguridad`.`Aplicaciones` (`idAplicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Aplicaciones_Usuarios_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SubSistemaSeguridad`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`InformacionTecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`InformacionTecnica` (
  `idInformacionTecnica` INT NOT NULL,
  `nombre_pc` VARCHAR(45) NULL,
  `mac_address` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  PRIMARY KEY (`idInformacionTecnica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SubSistemaSeguridad`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SubSistemaSeguridad`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `fecha_ingreso` DATETIME NULL,
  `fecha_cierre` DATETIME NULL,
  `accion` VARCHAR(45) NULL,
  `idInformacionTecnica` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idBitacora`),
  CONSTRAINT `fk_Bitacora_InformacionTecnica1`
    FOREIGN KEY (`idInformacionTecnica`)
    REFERENCES `SubSistemaSeguridad`.`InformacionTecnica` (`idInformacionTecnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bitacora_Usuarios1`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `SubSistemaSeguridad`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
